Invalid HTTP_HOST header: '128.199.13.193'. You may need to add '128.199.13.193' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '128.199.13.193'. You may need to add '128.199.13.193' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '128.199.13.193'. You may need to add '128.199.13.193' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '128.199.13.193'. You may need to add '128.199.13.193' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '128.199.13.193'. You may need to add '128.199.13.193' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '128.199.13.193'. You may need to add '128.199.13.193' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '128.199.13.193'. You may need to add '128.199.13.193' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '128.199.13.193'. You may need to add '128.199.13.193' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '128.199.13.193'. You may need to add '128.199.13.193' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '128.199.13.193'. You may need to add '128.199.13.193' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '128.199.13.193'. You may need to add '128.199.13.193' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '128.199.13.193'. You may need to add '128.199.13.193' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '128.199.13.193'. You may need to add '128.199.13.193' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '128.199.13.193'. You may need to add '128.199.13.193' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '128.199.13.193'. You may need to add '128.199.13.193' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '128.199.13.193'. You may need to add '128.199.13.193' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '128.199.13.193'. You may need to add '128.199.13.193' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '128.199.13.193'. You may need to add '128.199.13.193' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '128.199.13.193'. You may need to add '128.199.13.193' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '128.199.13.193'. You may need to add '128.199.13.193' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '128.199.13.193'. You may need to add '128.199.13.193' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '128.199.13.193'. You may need to add '128.199.13.193' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '128.199.13.193'. You may need to add '128.199.13.193' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '128.199.13.193'. You may need to add '128.199.13.193' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '128.199.13.193'. You may need to add '128.199.13.193' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/opt/work-app/.venv/lib/python3.12/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '128.199.13.193'. You may need to add '128.199.13.193' to ALLOWED_HOSTS.
